CHANGELOG.md, install
On CentOS 6.x by default the PATH variable does not contain the /usr/local/bin
=> CLOUD-642 Install cbd to a directory which is available on PATH

include/compose.bash
@lalyos 
Periscope uses the same /certs directory as default to read the certificates to access Ambari.
=> share certs volume with periscope

include/cloudbreak.bash
@akanto or @lalyos pls review...
* On osx the created certs directory's owner is ok, in linux case the certs directory's owner will be root, so we have to change it. For this the user have to be a sudoer.
* Other criteria: The user have to be in the 'docker' group.
=> CLOUD-41629: Change the created 'certs' directory's owner to the current user

docs/changelog.md, include/deployer.bash
See:
- https://github.com/sequenceiq/docker-gnused-linux-bin
- https://github.com/sequenceiq/gnused-osx-bin
- https://github.com/lalyos/glidergun-rack/blob/master/index/sed
=> Add gnu-sed 4.2.2 binary dependency

docs/changelog.md, include/cloudbreak.bash, test/cloudbreak.bash
=> consul recursors should exclude docker ip (boot2docker ip, or docker-machine ip)

include/cloudbreak.bash, include/migrate.bash
@akanto or @lalyos please review!
Changes:
- The `migrate` command was modified to only migrate the uaadb, because Cloudbreak and Periscope have their own runtime database migration mechanisms.
- The previous change requires the latest version from Cloudbreak and Periscope so I built and updated the defaults to use the latest development versions from the components' docker images.
=> Runtime migration

include/cloudbreak.bash
@lalyos or @akanto 
To Cloudbreak shell and CURLs work through https on local dev environment.
=> CLOUD-60634 modify cbd util local-dev to set labels for ambassador

include/cloudbreak.bash, include/compose.bash
custom traefik tls option:
all TLS is terminated by traefik. certificate and keyy is stored in: `$CBD_DIR/certs`.
By default the a cert(and key) is used which is always created for the communication channel between cloudbreak and the provisioned HDP cluster.
In case the cloudbreak deployment has its own DNS name (like prod/qa/preprod) you probably bring your own certificates. Copu them into: `$CBD_DIR/certs` and define a custome env var in `Profile`:
```
export CBD_TRAEFIK_TLS=/certs/seq-wildcard-2017-08.cer,/certs/seq-wildcard-2017-08.key
```
=> custom traefik tls option (for prod/qa/preprod)

Makefile
@lalyos plz review. On Go 1.7 i got the following error message: `-X flag requires argument of the form importpath.name=value`
=> Update build FLAGS syntax

include/cloudbreak.bash, include/compose.bash
@mhmxs please review
@biharitomi this also Fixes: #281
there is not even 1% startup time change between dbs:
- starting from migrated db (63,2 sec)
- starting from 1.2 db version migrationg up (64,3 sec)
- starting from epmty library/postgres (63,76 sec)
=> remove pre-warmed image dbs, use plain postgres

include/cloudbreak.bash
WIP: @biharitomi please review
3.6.0 had security issues: https://github.com/hortonworks/docker-cloudbreak-uaa/issues/3
```cbd util token``` works fine but login stucks at Oauth confirmation: https://192.168.64.37/sl/confirm
```
Login/confirm: Error from token server, code: 403
```
=> Use latest uaa from 3.6.x branch

include/deployer.bash
I've found that $CB_HOST_ADDRESS is set to http://$PUBLIC_ID and then, wait-for-cloudbreak curl command is not failing when Cloudbreak API is still not ready because Traefik is returning 302 to redirect to the HTTPS endpoint. Anyway, I think that a more general solution is to set curl to redirect and to ignore self signed certificates. This way you get a 302 followed by a 502 (Bad Gateway) when the Cloudbreak API is not ready for requests, making curl fail properly and fixing the `cbd start-wait` command.
=> Fix for wait-for-cloudbreak to follow redirects properly

include/cloudbreak.bash, include/compose.bash, include/env.bash
PERISCOPE_DB_HBM2DDL_STRATEGY -> PERISCOPE_HBM2DDL_STRATEGY
PERISCOPE_DB_TCP_ADDR -> PERISCOPE_DB_PORT_5432_TCP_ADDR
PERISCOPE_DB_TCP_PORT -> PERISCOPE_DB_PORT_5432_TCP_PORT
PERISCOPE_DB_USER -> PERISCOPE_DB_ENV_USER
PERISCOPE_DB_PASS -> PERISCOPE_DB_ENV_PASS
PERISCOPE_DB_NAME -> PERISCOPE_DB_ENV_DB
PERISCOPE_DB_SCHEMA_NAME -> PERISCOPE_DB_ENV_SCHEMA
@keyki pls do not merge until https://github.com/hortonworks/cloudbreak/tree/ssl-autoscale-db was not merged
=> CLOUD-93253 support ssl for periscope db

include/cloudbreak.bash, include/deployer.bash
Until we don't have the admin page to dynamically change these values the process is described in the doc which is really complicated and involves downloading sigil and generating files. With this new util command it is much more simple. The script still must be invoked by the user so he/she has the option to change the mapping.
=> BUG-98276 add util command to generate LDAP - OAuth2 mapping script

include/cloudbreak.bash
new registrator handles things little different, some extra configuration is needed for local development so the proxy/ambassador containers will be registered under the right service name in consul
=> BUG-100158 Cloudbreak on a different port local-dev fix for ambassadors service name

include/deployer.bash
IT runs with 
```
sudo ./cbd start-wait consul registrator identity commondb cloudbreak
```
since vault is not started the check will fail and return with exit code 1
=> BUG-112706 do not wait for vault when it's not requested

include/export.bash
IPTABLES rules cannot be collected if the user has no root privilages.
=> BUG-116863 Added root user as prerequisite for bundle collection

include/compose.bash
Introduce pg_stat_statements to get more statistical information from db. Removed privileged as well, I don't see any reason why a db shall be in privileged container.
https://www.citusdata.com/blog/2019/02/08/the-most-useful-postgres-extension-pg-stat-statements/
=> Intoduce pg_stat_statements to get more statistical information from db.

include/cloudbreak.bash
Extended run.sh in the identity image to import certificates from the /certs directory: https://github.com/hortonworks/docker-cloudbreak-uaa/blob/3.6.5-certs/run.sh#L9 The branch is based on 3.6.5-pgupdate
=> CB-988 Import mounted certificates to truststore at identity start

include/cloudbreak.bash, templates/compose-core-gateway.tmpl
- in case of mocked cb only environment
=> CB-716 gateway should redirect to /environments by default

templates/compose-environment.tmpl
Port 8087 has already taken by cloudbreak-redbeams container
please review @keyki @gregito
=> Fix cloudbreak-environment port expose

templates/compose-environment.tmpl
the `/etc/environment` is an already existing file in the base linux container which made invalid volume mount for the environment service
=> CB-1284 fix for invalid volume mount in the environment service compose

include/cloudbreak.bash
The URLs for the new environment and RDBMS (redbeams) services were reversed in the call to generate traefik.toml, causing routing to be incorrect. They are lined up correctly now.
=> CB-1289 Fix traefik.toml generation

templates/compose-redbeams.tmpl
Several environment variables necessary for redbeams to function within
a container are added. These cover authentication and vault access.
=> CB-1389. Add missing env vars for redbeams

include/deployer.bash
When cbd start is invoked with no list of services
(signifying that all service should be started), and
the commondb service has not started by the time it is
checked in deployer.bash, the list of services remains
empty. As a result, the check for whether the vault is
one of the services fails, and the vault is not
initialized.
With these changes, the guard has been updated to
initialize the vault when the list of services is empty.
=> CB-910. Vault is not initialized.

templates/compose-core-gateway.tmpl
no-stats points to a new 1.0.2 version, if that issue still occurs, merge this
=> Revert caddy to 1.0.1 version from 1.0.2

templates/compose-core-gateway.tmpl
1.0.1 seems slow, probably no-stats version pointed to 1.0.1-no-stats before
=> Use 1.0.1 caddy version with no-stats

Makefile, compose.go, deployer.go, functions.go, functions_test.go, include/cloudbreak.bash, include/compose.bash, include/db.bash, include/deployer.bash, include/env.bash, include/migrate.bash, templates/compose-datalake.tmpl, templates/compose-environments2-api.tmpl, templates/compose-idbmms.tmpl, templates/compose-main.tmpl, templates/traefik.toml.tmpl, traefik.go, traefik_test.go
Re-targeting for master / 2.13.
Notes:
* IDBMMS and Environments2 API Svc are both supported in `CB_LOCAL_DEV_LIST`
* 2 additional Docker containers are started for the new services: `cbreak_environments2-api_1` and `cbreak_idbmms_1`
* Environments2 API Svc can be used with official CDP CLI using `--endpoint-url http://localhost` and without explicitly providing `request_headers` in `~/.cdp/config`
* Both new services work fine with `mock-caas` using the changes of #6091 (2.13.0-dev.78)
* IDBMMS persists into the new DB `idbmmsdb` of `commondb`. Schema migration is not supported, and PostgreSQL schema name is assumed to be `public`. (These features / settings are not supported by IDBMMS.)
* There are two new `make` targets (`update-container-versions-cdpcp` and …
=> CB-2717 Add IDBMMS and Environments2 API Svc

Makefile
Follow-up to #605. Removing the `git tag` action as it may confuse other processes (e.g. CI/CD, tests, swagger-gen) that depend on the sole presence of `CB_VERSION` tags.
=> CB-2717 Remove git tag for CDPCP_VERSION

include/deployer.bash
Introduced a check if the license file is not present then the start and restart command will fail.
=> CB-3400 CBD start should fail when there is no license file

include/compose.bash
- same ear as before, but this customer does not want to have consul 8500 port exposed, only to the host machines
- consul 8500 is only open in dev mode now
=> EAR-11495 only open host port 8500 for consul if in dev mode

README.md
The `make bindata` step was added so that the README works the first
time on a system. The `go get` command was updated to only download
the source and not perform the build since the build requires bindata.
=> CB-4754 Fix README to work the first time on a system

compose.go, include/cloudbreak.bash, templates/compose-cadence.tmpl, templates/compose-main.tmpl
Cluster proxy HA functionality depends on cadence. Cadence was added
to cloudbreak-deployer.
This was manually tested by running cloudbreak deployer locally.
=> CB-6445: Add cadence to cloudbreak-deployer for cluster proxy HA

include/cloudbreak.bash, include/compose.bash
Tested scenarios:
- start from scratch
- start from previous version of cbd(posgtres also) with data
- downgrade to previous version requires password configs for database dependent services, but it could be done through Profile
=> CB-6473 use UAA default secret as Postgres default password

templates/compose-datalake.tmpl, templates/compose-freeipa.tmpl
The freeipa service now includes SDX endpoint and SDX service now includes
cluster proxy url. Both of which are needed for OID sync work.
=> Add configuration needed for OID sync

include/cloudbreak.bash
FreeIPA HA registration with cluser proxy was producing intermittent
errors. Cluster proxy was updated in 2.1.0.0-316 to scale to more
nodes. This updates cbd to use this the fixed version.
=> CB-8035: Use cluster proxy 2.1.0.0-316

templates/compose-core-gateway.tmpl, templates/compose-thunderhead-mock.tmpl
Redirecting address: [https://localhost/auth/in?redirect_uri=https://localhost/environments](https://localhost/auth/in?redirect_uri=https://localhost/environments). However the correct and latest is [https://localhost/thunderhead/auth/in?redirect_uri=https://localhost/environments](https://localhost/thunderhead/auth/in?redirect_uri=https://localhost/environments).
So we fix this at the Cloudbreak Deployer repository.
=> CB-8085 localhost login and logout redirect need to be updated

include/cloudbreak.bash
As we have added new endpoints to the public APIs to generate CDP CLI
commands, we needed to bump version here to use the newer Docker images.
=> CB-8805 Add new public API images

include/cloudbreak.bash, templates/compose-main.tmpl, templates/traefik.toml.tmpl, traefik.go, traefik_test.go
- uluwatu is using the http endpoint because it was unreliable on udp
- 2 new jaeger ports opened
- 5778 for serving configs to traefik
- 14268 http collector endpoint for uluwatu
=> CB-9075 & CB-9047 - added tracing to traefik and uluwatu 

include/cloudbreak.bash
CB-9170, CB-9169 - new line separator and profile tag on generated cli commands
=> CB-9170, CB-9169 - new line separator and profile tag on generated cli commands

include/cloudbreak.bash
This reverts commit 3b5efbbef660c09682707c32afe926978f7d0b73.
See CDPAM-1103 for details.
=> Revert "Update cluster proxy version to 2.1.0.0-393"

include/cloudbreak.bash
CB-9229 - ability to create idbroker mapping creation CDP CLI command for a non-existing environment
=> CB-9229 - ability to create idbroker mapping creation CDP CLI command for a non-existing environment

include/cloudbreak.bash
CB-9474 - cli throws unrecognised field exception for env cli command generation for response in CloudSubnet
=> CB-9474 - cli throws unrecognised field exception for env cli command generation for response in CloudSubnet

include/cloudbreak.bash
ULU_AUDIT_ADDRESS seems wrong by testing in CBD
To allow uluwatu container and server.js properly reach the audit api it has to be changed to
“ULU_AUDIT_ADDRESS=http://audit-api:8982”
=> CB-9602 Fixing uluwatu's audit api port

include/cloudbreak.bash, templates/compose-datalake-api.tmpl, templates/compose-distrox-api.tmpl, templates/compose-environments2-api.tmpl
So far debugging of CB public endpoints' code was not resolved. The public endpoint services however are provisioned for the usage of debug flag and debug port.
This is now introduced in CBD.
There were wrongly configured hosts (cb and autoscale) in public services docker containers, this is also going to be fixed.
=> CB-9874 Make cdp public endpoint service locally debuggable

include/env.bash, templates/compose-cloudbreak.tmpl, templates/compose-datalake.tmpl, templates/compose-environment.tmpl, templates/compose-freeipa.tmpl, templates/compose-redbeams.tmpl
eventually the cb-enabled platforms can be removed once this version reaches prod
=> CB-11217 Extracted all platform configs under cdp: namespace

templates/compose-environment.tmpl
Reverts hortonworks/cloudbreak-deployer#716
=> Revert "CB-11254 - update cbd with new cb image to introduce mock infrastructure changes"

Makefile, include/cloudbreak.bash
Update all Thunderhead dependencies to version 1.0.0-b3470.
=> CB-11544 Updated CDPCP container versions to 1.0.0-b3470

include/cloudbreak.bash
Update all Thunderhead dependencies to version 1.0.0-b3518.
=> CB-11152 Updated CDPCP container versions to 1.0.0-b3518

templates/traefik.toml.tmpl
In order to mock IAM calls when running thunderhead-mock locally.
=> CB-12176 Add /iam to thunderhead-api-frontend.routes

include/cloudbreak.bash, templates/compose-main.tmpl
v13 is not compatible with v9.
If you don't want to preserve your local data then just remove the cbreak_common volume with the `cbd delete` or the `docker volume rm cbreak_common` command.
If you want preserve your local dev database please follow these steps:
```
docker kill + stop the services in Idea
cbd startdb
docker ps -> check the postgres version, should be 9.6.16-alpine
docker exec -it -u postgres cbreak_commondb_1  pg_dumpall > dbdumpfile
save the vault keys from your Profile (VAULT_ROOT_TOKEN, VAULT_UNSEAL_KEYS)
cbd kill
docker volume rm cbreak_common
upgrade your cbd
cbd regenerate
cbd startdb
docker ps -> check the postgres version, should be 13.2-alpine
docker logs cbreak_commondb_1 -> check that the db started
check that the db is empty ('docker exec -itu postgres …
```
=> CB-11989 RDS: Upgrade cloudbreak PostgreSQL from v9 to v13

include/cloudbreak.bash, include/env.bash, templates/compose-main.tmpl
Follow-up to #730. The thunderhead service WorkloadIam used to be always started so far. Since this service is non-essential for everyday development via CBD (unless testing some specific user-sync use cases that need WorkloadIam), the startup of WorkloadIam is made optional here. In particular, CBD service `workloadiam` / Docker container `cbreak_workloadiam_1` will only be started if the new `Profile` setting `WORKLOADIAM_ENABLED` is set to `true`. This flag defaults to `false`, so omitting the setting in `Profile` has the same effect as including the following statement:
```
export WORKLOADIAM_ENABLED=false
```
To enable WorkloadIam container creation, add the following to your CBD `Profile`:
```
export WORKLOADIAM_ENABLED=true
```
Irrespective of the value of `WORKLOADIAM_ENABLED`, …
=> CB-12709 Put WorkloadIam container creation behind a flag

README.md
When building cbd from scratch with go 1.11 or later, modules must
either be used or the module must be disabled. This procedure change
disables modules so the build works from a fresh checkout.
This was manually tested.
=> CB-14041: Fix cbd build procedure from scratch

include/compose.bash
Closes [CB-12982](https://jira.cloudera.com/browse/CB-12982).
Check if Docker daemon is running by doing a ps before running `docker-compose` commands.
Changes the output from this:
```
$ cbd ps
[43686] Failed to execute script docker-compose
Traceback (most recent call last):
File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
File "http/client.py", line 1252, in request
File "http/client.py", line 1298, in _send_request
File "http/client.py", line 1247, in endheaders
File "http/client.py", line 1026, in _send_output
File "http/client.py", line 966, in send
File "site-packages/docker/transport/unixconn.py", line 43, in connect
ConnectionRefusedError: [Errno 61] Connection refused
During handling …
```
=> CB-12982: Check if docker is running with a ps command.

include/cloudbreak.bash
Related to Jira: https://jira.cloudera.com/browse/CDPSDX-3221 as this will help fix the Datalake-DR service on CBD.
=> CDPSDX-3221: Updated Thunderhead image tags to a more recent build.

compose.go, compose_test.go, functions.go, functions_test.go, traefik.go, traefik_test.go
Jira: https://jira.cloudera.com/browse/CDPSDX-3219
I specifically faced this issue when trying to run the **datalake-dr** service locally resulting in CBD not deploying the **datalake** container.
I basically just added a Regex which matches the only 4 possible cases I could think of where a service is truly in the local list:
1. "CB_LOCAL_DEV_LIST=_service_"
2. "CB_LOCAL_DEV_LIST=other_services,_service_"
3. "CB_LOCAL_DEV_LIST=_service_,other_services"
4. "CB_LOCAL_DEV_LIST=other_services1,_service_,other_services2"
Where each of those cases can have any number of spaces before or after the service names.
I added this logic to:
- Logic that generates service URLs
- Logic that generates the docker-compose file
- Logic that generates the traefik file
In case this is expected behavior, …
=> CDPSDX-3219: Added Regex to logic for checking if service is local to avoid mismatch of substrings.

include/cloudbreak.bash
another property disappeared during conflict resolution from cloudbreak.bash.
```
consumption:
...
image: :2.57.0-b30
```
Now it's pulling the correct image:
`docker-private.infra.cloudera.com/cloudera/cloudbreak-consumption:2.57.0-b30`
```
image: docker-private.infra.cloudera.com/cloudera/cloudbreak-consumption:2.57.0-b30
command: bash
deploy:
resources:
limits:
memory: 2048M
cpus: 4.0
```
=> CB-16674 docker compose is not generated properly

include/cloudbreak.bash
Error found by @biharitomi :
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/sequenceiq/consumption/configuration/DatabaseConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: FATAL: database "consumptiondb" does not exist
```
Validated the changes, cbd now creates consumptiondb 🥇
=> CB-16674 added consumption to db-init scripts

include/cloudbreak.bash, templates/compose-thunderhead-mock.tmpl
Jira: https://jira.cloudera.com/browse/CDPSDX-3638
Very simple, this will allow us to run mock tests with datalake DR using CBD.
=> CDPSDX-3638: Expose mock DR service in thunderhead mock container.

include/cloudbreak.bash, templates/compose-datalake.tmpl, templates/compose-thunderhead-mock.tmpl
Jira: https://jira.cloudera.com/browse/CDPSDX-3642
Objective of this is to pass in a new environment variable to the Datalake service which specifies the endpoint for the mock DR service.
=> CDPSDX-3642: Add a new endpoint variable for the mock DR service which will be passed into the Datalake container.

include/cloudbreak.bash, templates/compose-datalake.tmpl
Jira: https://jira.cloudera.com/browse/CDPSDX-3648
=> CDPSDX-3648: Revert use of mock datalake dr endpoint in order to use a more simplified approach.

include/cloudbreak.bash
Jira: https://jira.cloudera.com/browse/CB-18352
=> CB-18352: Updated Thunderhead container versions to b7581.

include/cloudbreak.bash, templates/compose-cadence.tmpl
The version is very old, the new version also supports GRPC communication which is a new standard for our Thunderhead services, especially in FedRAMP.
=> Update Cadence default version to the version being used in mow-dev/int/stage/prod.
