hortonworks/cloudbreak-deployer

README.md
Updating readme.md as mentioned in the issue #33
=> Malathit90 patch 1

CHANGELOG.md, README.md, include/cloudbreak.bash, include/compose.bash
AWS keys are not configurable from Profile
=> AWS keys are not configurable from Profile

include/cloudbreak.bash
=> update periscope version, logback fix

include/cloudbreak.bash, include/compose.bash
=> CLOUD-510 use /dev/urandom

CHANGELOG.md, CONFIGURATION.md, include/cloudbreak.bash, include/compose.bash, include/deployer.bash
@lalyos 
Cloudbreak will require a TLS client certificate after https://github.com/sequenceiq/cloudbreak/pull/730 is merged.
=> generate cloudbreak certificate for TLS setup

include/cloudbreak.bash, include/compose.bash
=> Using fix version of ambassador until cbd doesn't support new version: connectable

include/cloudbreak.bash
=> missing ambassador version fix in local-dev

include/compose.bash, include/deployer.bash, include/migrate.bash
@akanto or @lalyos pls review...
=> CLOUD-933: create only compose-yaml for migration

docs/index.md
Hi,
This is a PR following this issue: https://github.com/sequenceiq/cloudbreak-deployer/issues/96
I hope it helps other people in the future. It's a particular nasty issue as some connections between containers work, but others don't, so it's not obvious to find what's going on.
Cheers,
François
=> clarified README.md about potential firewall issues (CentOS 7, possibly others)

docs/changelog.md, include/cloudbreak.bash
=> Fixing cb-shell authentication

docs/changelog.md, include/cloudbreak.bash, include/deployer.bash, test/cloudbreak.bash
fully using the fact that gnu-sed 4.2.2 is provided
basht tests added
=> rework recursor handling to be more robust

docs/changelog.md, include/cloudbreak.bash, include/compose.bash, include/deployer.bash, include/migrate.bash
=> CLOUD-42447: new command for seamless db migration: start-and-migrate

include/cloudbreak.bash
=> CLOUD-43356: cbd util local-dev will execute migration if CB_SCHEMA_SCRIPTS_LOCATION is set otherwise do nothing

include/cloudbreak.bash, include/compose.bash
=> Using DNS SRV records for service address resolving instead of ambassador

docs/changelog.md, include/compose.bash
=> CLOUD-41906: remove ambassador

docs/changelog.md, include/cloudbreak.bash, include/deployer.bash
=> CLOUD-42447: remove '--no-migrate'

docs/changelog.md
@akanto @fschneider i tried to move changes since 1.0.3 to the new unreleased section, please double check.
=> fixing missed 1.0.3 release

deployer.go, include/azure-tools.bash, include/deployer.bash
@lalyos pls review.
This pr implement dash deploying and azure resource manager app configuration on automated way.
=> CLOUD-43927 added azure cli commands

include/azure-tools.bash
=> increased version on azure-cli-tools

docs/changelog.md, docs/configuration.md
=> CLOUD-43927 added changelog

docs/changelog.md, include/cloudbreak.bash, include/compose.bash, include/deployer.bash, include/migrate.bash
@akanto pls check.
Uaa migartion process added
=> CLOUD-44323 added ability to define scopes

Dockerfile.integrationtest, Makefile, include/cloudbreak.bash, include/deployer.bash, integration-test/generate.bash
Tested on a vanilla aws instance
=> Integration test

include/azure-tools.bash
=> azure-cli-tools version upgraded

docs/changelog.md, include/cloudbreak.bash, include/compose.bash
=> CLOUD-46704 Mail sending does not work, add new parameters

include/compose.bash
=> CLOUD-46866 Sultans service id at Uluwatu compose

include/cloudbreak.bash
=> CLOUD-43757 apply changes that are required by upgrading UAA to 2.7.1

include/cloudbreak.bash
=> Update docker image versions related to rc-1.1

docs/changelog.md, install-latest
=> fixing install scripts

docs/development.md, include/cloudbreak.bash
@keyki or @akanto please review!
=> CLOUD-43757 make uaa zone domain configurable

docs/kerberos.md, docs/periscope.md, docs/spi.md, mkdocs.yml
- minor cleanup
- calls out Tech Preview features
- moving from Periscope to Auto-scaling
=> Minor cleanup

include/migrate.bash
@akanto or @schfeca75 please check!
=> CLOUD-48442 do not log error when migration result is empty

include/cloudbreak.bash
=> CLOUD-48453 Update Uluwatu container

include/azure-tools.bash
=> CLOUD-48609 azure cli logs on host machine

include/azure-tools.bash
=> CLOUD-48909 new azure-cli-tools version to be able to deploy dash

include/cloudbreak.bash, include/compose.bash, include/deployer.bash, include/docker.bash
=> CLOUD-49856 Avoid using /tmp from cbd

docs/changelog.md, include/cloudbreak.bash, include/deployer.bash
=> CLOUD-51258 added cloudbreak shell show command

docs/onprem.md
=> CLOUD-51567 fixed onprem doc

include/cloudbreak.bash
@lalyos updated container versions
=> Updated container versions

include/cloudbreak.bash, test/cloudbreak.bash
=> CLOUD-51948 cbd fails to parse resolv.conf with comments

README.md
=> CLOUD-51312 remove github readme

include/cloudbreak.bash, include/compose.bash, include/migrate.bash
=> CLOUD-51251 support for separated mybatis and app related migration SQLs

include/deployer.bash
@akanto plz review i checked the solution with @lalyos
=> CLOUD-51905 Enable azure and aws commands without Profile

include/deployer.bash, include/migrate.bash
=> CLOUD-51310 Do not execute the uaa migration sql automatically

include/cloudbreak.bash, include/compose.bash
=> CLOUD-53134 uluwatu container changed

include/cloudbreak.bash
=> update docker images to the latest dev ones

include/cloudbreak.bash
=> CLOUD-52739 Add sssdconfig scopes to uaa.yml

include/cloudbreak.bash
=> CLOUD-51506 Add scope for topology/platform

include/cloudbreak.bash
=> updated containers

include/cloudbreak.bash
=> update container versions to 1.2.4

include/deployer.bash
=> eliminate curl outputs of init command

include/deployer.bash
@lalyos, @doktoric  plz review
=> CLOUD-57781 Use private ip as public if hostname not found on AWS

dev-docs/cloudbreak-development.md, include/deployer.bash, include/docker.bash
=> CLOUD-45606 make cdb doctor docker-machine compatible

include/deployer.bash
=> CLOUD-58616 Disallow update if there is no Profile

include/deployer.bash
=> CLOUD-57781 Fix boot2docker ip resolving as public IP

include/cloudbreak.bash
=> Included new default blueprint

include/compose.bash
=> CLOUD-60308 share /etc/cloudbreak dir with cloudbreak

include/cloudbreak.bash, include/compose.bash
=> CLOUD-41893 set sultans base path to '/sl' and uaa to '/identity'

include/cloudbreak.bash, include/compose.bash
=> CLOUD-60536 New catatnight/postfix container for email sending

include/cloudbreak.bash
=> CLOUD-61012 Update cloudbreak-shell-remote to follow changes

include/cloudbreak.bash
=> CLOUD-61198 Fix cloudbreak-shell-remote command

include/docker.bash
=> CLOUD-61226 add DOCKER_MACHINE parameter to docker-machine status check

include/cloudbreak.bash
=> CLOUD-61632 cbd delete ignores CB_DB_ROOT_PATH on linux machine

include/cloudbreak.bash
=> include periscope in local-dev command

include/cloudbreak.bash
=> hide error message if there is no container to delete

include/cloudbreak.bash, include/compose.bash
=> CLOUD-61230 Add multiple traefik.frontend.rule on AWS

Makefile
=> added update-container-versions goal to Makefile

include/cloudbreak.bash, include/compose.bash
@akanto, @doktoric plz review. Those are our "static" containers as i know.
=> CLOUD-58620 Move every docker container from sequenceiq to hortonworks

include/cloudbreak.bash
=> CLOUD-64897 upgrade UAA to 3.6.0

include/compose.bash
=> pull cloudbreakshell also

include/compose.bash
=> use grouping instead of herestring

include/cloudbreak.bash, include/compose.bash
@biharitomi please merge if the default use case is verified
=> Make uaa db params configurable from Profile

include/deployer.bash
=> cbd start hdc-cli download fix

include/cloudbreak.bash, include/compose.bash
@martonsereg please review and you could also give a try to the solution :)
=> Includes smartsense for cloudbreak container into docker compose

include/cloudbreak.bash, include/compose.bash, include/deployer.bash
@martonsereg or @lalyos please take a look
=> CLOUD-60527 runnable command of smartsense for cbd

include/cloudbreak.bash, include/compose.bash
=> CLOUD-66647 CB_IMAGE_CATALOG_URL can be overwritten in Profile

include/cloudbreak.bash, include/compose.bash
=> CLOUD-66888 Set cloudbreak public ip

include/cloudbreak.bash, include/compose.bash
=> CLOUD-67182 new env variable for default inbound security group on aws

include/deployer.bash
=> CLOUD-68063 Disable cbd update <xyz>

include/deployer.bash
=> CLOUD-68579 Do not write user password to any log files

include/cloudbreak.bash, include/compose.bash
=> CLOUD-68586 Autoscaling History does not auto-refresh

include/compose.bash
Hi,
Please merge it.
thanks
gabo
=> cbd gracefull kill container, use docker-compose stop instead of kill

include/compose.bash
=> CLOUD-73608 enabled platforms parameter in profile

include/cloudbreak.bash, include/compose.bash
efault email password if UAA_DEFAULT_USER_PW is empty
=> CLOUD-74655 D

include/cloudbreak.bash, include/compose.bash
=> CLOUD-75338 Uprade traefik docker image to v1.1.2

include/cloudbreak.bash, include/compose.bash
=> CLOUD-75962 Periscope DB config parameters

include/cloudbreak.bash
=> CLOUD-75962 default value: public for db schema

include/cloudbreak.bash
=> CLOUD-76680 fixed cb host address

include/cloudbreak.bash
=> CLOUD-76680 use http for polling

include/cloudbreak.bash, include/compose.bash
=> added custom image configuration

include/cloudbreak.bash
=> CLOUD-76876 add 'periscope.cluster' scope to 'cloudbreak_shell' oauth client

include/cloudbreak.bash, include/compose.bash
=> traefik fix

include/cloudbreak.bash, include/deployer.bash
@bbihari or @mhmxs 
It depends partly on https://github.com/sequenceiq/cloudbreak/pull/2383
=> Create command and Oauth client for retreiving flex usage from Cloudbreak

include/cloudbreak.bash
The PR depends on https://github.com/sequenceiq/cloudbreak/pull/2391
=> CLOUD-75554 parameter to get latest flex usages for get-usages command

include/cloudbreak.bash
=> Fix get-usage command by remove new lines from basic credentials

include/cloudbreak.bash
=> use only UAA related confs for get-usage command and upgrade SmartSense

include/cloudbreak.bash
=> CLOUD-80146 uaa yml with preconfigured max active connection

include/cloudbreak.bash, include/compose.bash
=> CLOUD-80176 fixed common db issue

include/cloudbreak.bash
=> CLOUD-81771 update SmartSense container version to 0.7.0

include/cloudbreak.bash, include/compose.bash, include/deployer.bash
Depends on: https://github.com/sequenceiq/amazon-cbd-quickstart/pull/90
=> CLOUD-81858 Start SmartSense with other services

include/cloudbreak.bash, include/compose.bash
=> Added more endpoint

include/cloudbreak.bash, include/compose.bash, include/deployer.bash
=> CLOUD-84174 setup logrotation for docker container logs

include/compose.bash
=> CLOUD-88126 rotate the logfiles in ./logs dir and its subdirs

include/compose.bash
=> CLOUD-83892 cb java opts escaped

include/compose.bash
=> fixed escaping in compose

include/deployer.bash
=> aws needs profile

include/cloudbreak.bash, include/env.bash
=> BUG-96678 UAA default group removed

include/cloudbreak.bash, include/compose.bash, include/env.bash
Configuration parameter for: https://github.com/hortonworks/cloudbreak/pull/3474
=> BUG-101476 Configuration parameter for max retry count for salt in case of error

include/db.bash, include/deployer.bash
Changes:
- simplified db initialization
- file based db dumps
- restore db dump from file
- fix the initialization to get db names from env variables
=> BUG-104950 use file based database dump and restore mechanism

include/cloudbreak.bash, include/compose.bash, include/deployer.bash, include/env.bash
The purpose of this PR is not to generate Cloudbreak and Periscope services into the docker-compose file so the proxies can be launched directly.
=> simplified dev setup

include/compose.bash
This will also fix the TLS issue
=> remove proxies with cbd kill

include/vault.bash
fixes crypto/x509: CPU denial of service in chain validation
https://github.com/hashicorp/vault/blob/master/CHANGELOG.md
=> update Vault to fix security issues

include/cloudbreak.bash, include/compose.bash, include/db.bash, include/deployer.bash, include/env.bash, include/migrate.bash
Depends on: https://github.com/hortonworks/cloudbreak/pull/4609
=> CB-3 Migration for Datalake service

include/deployer.bash
=> CB-487 Configure db environment variables before remove the docker volumes

include/cloudbreak.bash, include/env.bash
now that CLI works we should enabled UMS by default so everything can function
=> CB-1002 UMS is enabled by default for local dev environment

Makefile, compose.go, compose_test.go, include/cloudbreak.bash, include/compose.bash, include/db.bash, include/deployer.bash, include/env.bash, include/migrate.bash, templates/compose-main.tmpl, templates/compose-redbeams.tmpl, templates/traefik.toml.tmpl, traefik.go, traefik_test.go
The deployer now has the ability to manage a container running the
new Redbeams service, along with its database.
=> CB-1095 Add redbeams

include/migrate.bash
fix migrate related syntax error
=> fix migrate related syntax error

Makefile, compose.go, compose_test.go, include/cloudbreak.bash, include/compose.bash, include/db.bash, include/deployer.bash, include/env.bash, include/migrate.bash, templates/compose-freeipa.tmpl, templates/compose-main.tmpl, templates/traefik.toml.tmpl, traefik.go, traefik_test.go
=> CB-1285: New microservice: freeipa-service

templates/compose-environment.tmpl
Fix environment service port mapping
=> Fix environment service port mapping

include/deployer.bash
Reverts hortonworks/cloudbreak-deployer#567
=> Revert "CB-1543 added enchanced start wait"

templates/compose-environment.tmpl, templates/traefik.toml.tmpl, traefik_test.go
=> CB-1617 rename path for env

include/deployer.bash
CB-1617 fix start-wait path for env service
=> CB-1617 fix start-wait path for env service

templates/compose-datalake.tmpl, templates/compose-redbeams.tmpl
CB-2794 – added new env variables for datalake and redbeams
=> CB-2794 – added new env variables for datalake and redbeams

templates/compose-datalake.tmpl, templates/compose-redbeams.tmpl
This reverts commit 70df753e1878dfffc8dcbd7cd9c3d999f4620007.
=> Revert "CB-2794 – added new env variables for datalake and redbeams"

include/cloudbreak.bash, include/compose.bash
- If customer creates a file in the location `./etc/custom-consul-config.json` it will be applied to consul
- not sure where should we document this
=> EAR-11495 added option for users to provide custom configuration for consul

include/cloudbreak.bash, templates/compose-cluster-proxy.tmpl
- upgraded cluster proxy image version
- added tunnel (CCM) environments variables
=> CB-4296 Cluster proxy CCM integration

templates/compose-freeipa.tmpl
=> CB-4041 setup default gateway cidt for freeipa as well

include/deployer.bash
Please review and merge if it is OK for you.
=> CB-5290 Remove obsolete compose-pull

include/cloudbreak.bash, templates/compose-environments2-api.tmpl
=> CB-6459 env2-api-service can be run using local development folders

include/cloudbreak.bash, templates/compose-cadence.tmpl, templates/compose-cluster-proxy.tmpl
Update the cluster proxy version to support the HA functionality.
=> CB-4377: Update cluster proxy to enable HA

include/cloudbreak.bash, templates/compose-cluster-proxy.tmpl
Wait for @jamisonbennett 's approval
=> add cbreak prefix to CP health check worker container

include/cloudbreak.bash
ALTCORE-3463 - update public api versions
=> ALTCORE-3463 - update public api versions

include/cloudbreak.bash
ALTCORE-3464 - bump up versions due to environment and datalake public api changes
=> ALTCORE-3464 - bump up versions due to environment and datalake public api changes

include/cloudbreak.bash
ALTCORE-3470, CB-9118 - deserialization fix on cdp cli command generate
=> ALTCORE-3470, CB-9118 - deserialization fix on cdp cli command generate

templates/compose-main.tmpl
Make Redbeams URL available for Uluwatu
=> CB-10038 Add ULU_REDBEAMS_ADDRESS

include/cloudbreak.bash, include/env.bash, templates/compose-environment.tmpl
=> CB-11135 Add External Experiences delete enabled flag

templates/compose-audit.tmpl
Environment service host and port was wrongly configured, this is fixed now.
=> CB-11376 Fix local audit service config

include/cloudbreak.bash, include/env.bash, templates/compose-cluster-proxy.tmpl
Reverts hortonworks/cloudbreak-deployer#743
=> Revert "CB-14337 Add inverting proxy host to the hosts file of cluster-proxy …"

include/cloudbreak.bash, templates/compose-datalake-dr.tmpl
Jira: https://jira.cloudera.com/browse/CDPSDX-3222
=> CDPSDX-3222: Added DATALAKE_DR_TARGET_PATH variable in order to make local development easier.

include/deployer.bash
Jira: https://jira.cloudera.com/browse/CDPSDX-3344
See below for what this change entails, but basically we have had a lot of issues updating CBD to what we need for local development. This change will hopefully allow for more flexibility and easier dev use of the application.
=> CDPSDX-3344: Added update-to-dev and update-to-build commands.

include/cloudbreak.bash
Jira: https://jira.cloudera.com/browse/CB-19126
=> CB-19126 Updated Thunderhead image versions to b8492

include/deployer.bash
Apparently it's broken, see Slack conversation: https://cloudera.slack.com/archives/CF66M7WP6/p1670221499075289
=> Update yq version to 4.30.5 as it's broken on some macos versions
